version: '3.5'
services:
  angular:
#    user: www-data:www-data
    container_name: cesi-scheduler-frontend-angular
#    build:
#      .
    image: registry.gitlab.com/cesiap18/cesisheduler/frontend
    working_dir: /app
    volumes:
      - '.:/app'
#      - '/app/node_modules'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
